int atd_cmd_dial(int fd, char *num);
int atd_cmd_hangup(int fd);
int atd_cmd_answer(int fd);
int atd_cmd_call_events(int fd);
int atd_cmd_sms_events(int fd);
int atd_cmd_submit(int fd, char *num, char *msg);
int atd_status_call(int fd, enum callstatus status, char *num);
int atd_status_delivered(int fd, char *num, char *msg);
ssize_t dec_str(char *in, char **out);
int dec_call_status(int fd, struct call *calls);
int dec_sms_status(int fd, struct sms *sms);
int xwrite(int fd, char *buf, size_t len);
int xread(int fd, char *buf, size_t len);
